name: Integration

on:
  push:   # run on every branch push
    branches: ['**']
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php-version: ["8.3", "8.4"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          tools: pecl, phpize, php-config
          coverage: none

      - name: Build & Test extension
        run: |
          set -e
          php -v
          php-config --extension-dir
          phpize
          ./configure
          make -j"$(getconf _NPROCESSORS_ONLN)"
          sudo make install
          echo "extension=normalizer.so" > normalizer.ini
          php -d zend.assertions=1 -d assert.exception=1 -dextension=normalizer.so --ri normalizer
          make test TESTS="--show-diff" || exit 1
      - name: Show extension info
        run: php -dextension=normalizer.so --ri normalizer

      - name: "Error log"
        if: ${{ failure() }}
        run: "ls -1t tests/*.log | xargs -d'\n' cat"

      - name: "Error diff"
        if: ${{ failure() }}
        run: |
          for FILE in $(find tests -name '*.diff'); do
            echo $FILE
            cat $FILE
            echo
          done
